backend:
  name: git-gateway
  branch: main # La rama principal de tu repositorio

media_folder: "assets/uploads" # Carpeta para imágenes
public_folder: "/assets/uploads"

collections:
  - name: "pages" # Nombre de la colección
    label: "Pages" # Etiqueta visible en el CMS
    folder: "content/pages" # Carpeta donde se guardarán los archivos
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
